### ISSUE TITLE
Feature required

### ISSUE THREAD

**Issue by Edenharder** [MarkHedleyJones/dmenu-extended#114]
Thank you for dmenu-extended, it's very convenient. Is it possible to add a function to quit the running applications? With a keyword like "quit" or a symbol like "\".

**Comment by Fuseteam** [comment]
wait what? doesn't demu close after it runs the application?

**Comment by Edenharder** [comment]
@Fuseteam Thank you for the suggestion! Just a reminder for other users.
1.  `<name-of-application>` is not the exact the `Name` part in the desktop file, but the real name of the program, which is usually in `/usr/bin`. For example, the `Name` part in the desktop file of `/usr/bin/skypeforlinux` could be `Skype Preview`.
2. `;` should be appended to the command, that is, `killall <name-of-application>;`.
