### ISSUE TITLE
Cannot open application when there are space in `Name` in the desktop file

### ISSUE THREAD

**Issue by Edenharder** [MarkHedleyJones/dmenu-extended#116]
For example, the default name of the application `owncloud` is
```
Name = owncloud desktop sync client
```
When we select `owncloud desktop sync client` in the list of `dmenu-extended`, nothing happens. If we do the change
```
Name = owncloud
```
and rebuild the cache. When we select `owncloud in the list of `dmenu-extended`, everything works fine. 

Similar issue exists for other applications also, for example `Skype for linux`.

**Comment by Fuseteam** [comment]
this bug seems familiar.....

**Comment by Fuseteam** [comment]
ah right there was a similar bug with files and exec paths but seems unrelated

**Comment by MarkHedleyJones** [comment]
The issues appears to be that the owncloud `.desktop` file had some extra whitespace at the end of it's name which was being stripped when received from the menu, but was still present in the cache (so wasn't matching the entered command with the aliased command). Anyway I've pushed some changes so feel free to try the new version and let me know if you still have any issues.

**Comment by zpxuxpz** [comment]
@MarkHedleyJones Thank you! It works now.

**Comment by Edenharder** [comment]
Thank you! It works now.
