### ISSUE TITLE
Question: How do I exclude all directories from dmenu?

### ISSUE THREAD

**Issue by fromtheeast710** [MarkHedleyJones/dmenu-extended#125]
I have tried 
`"exclude_items": ["/*"],`
`"global_ignore_folders": ["/*"],`
`"ignore_folders": ["/*"],`
but that doesn't seem to work

**Comment by fromtheeast710** [comment]
Nevermind, that worked.

**Comment by MarkHedleyJones** [comment]
Glad you found the solution.
Was the issue that you hadn't rebuilt the cache after changing the settings?

**Comment by MarkHedleyJones** [comment]
The names are extracted from the `.desktop` file for the relevant application.
For example, here's one for Arduino:
```
[Desktop Entry]
Type=Application
Name=Arduino IDE
GenericName=Arduino IDE
Comment=Open-source electronics prototyping platform
Exec="/home/mark/Downloads/arduino-1.8.19-linux64/arduino-1.8.19/arduino"
Icon=arduino-arduinoide
Terminal=false
Categories=Development;IDE;Electronics;
MimeType=text/x-arduino;
Keywords=embedded electronics;electronics;avr;microcontroller;
StartupWMClass=processing-app-Base
```
