### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by nabsiddiqui** [MarkHedleyJones/dmenu-extended#30]
Is there a way I can donate to this program?  If so, please let me know here or through private message.  I use this program everyday and it sames me an immense amount of time.  

For example, I no longer have to use bash scripts for example to do basic things like launch a bunch programs.  I just add them as aliases and it works great!  I would love to donate.

**Comment by markjones112358** [comment]
Thanks, I'm flattered.
I'll have to do a bit of research into donation platforms and check the feasibility of accepting them.
Really, just knowing that people are using it and that it is saving people time is rewarding enough at the moment.

**Comment by nabsiddiqui** [comment]
Well thank you for the great work on this.  I use it everyday.  The aliases really help me do a lot of stuff.  For instance, thanks to weird quirks in Linux, I often find myself having to restart network applets or dropbox applets, etc.  Now I just set the terminal commands as aliases in dmenu_extended and fix those errors very quickly.  I could probably do this with bashrc, but this is much quicker.  Please message me a PayPal address if you change your mind.

**Comment by ckdarby** [comment]
@markjones112358 Thank you for making this :+1:

**Comment by markjones112358** [comment]
Thanks for posting! Glad you're getting use from it.

**Comment by MarkHedleyJones** [comment]
Patreon page set-up for donations, note added to bottom of README.md.

**Comment by ckdarby** [comment]
@MarkHedleyJones Dmenu helped me a lot back in the day. These days I've been using Rofi.

Thank you, hope you continue supporting those using dmenu :)
