### ISSUE TITLE
Unicode paths are not handled correctly

### ISSUE THREAD

**Issue by edi9999** [MarkHedleyJones/dmenu-extended#38]
After waiting for sometime for the cache to be built, I get the following error : 

```
Traceback (most recent call last):
  File "/usr/local/bin/dmenu_extended_cache_build", line 6, in <module>
    dmenu_extended.dmenu().cache_build()
  File "/usr/local/lib/python2.7/dist-packages/dmenu_extended.py", line 938, in cache_build
    for root, dirs , files in os.walk(foo, followlinks=follow_symlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb4 in position 1: ordinal not in range(128)
```

It seems it is a known issue with os.walk : see this stackoverflow question : http://stackoverflow.com/questions/21772271/unicodedecodeerror-when-performing-os-walk

You can reproduce the issue locally by running the following in your shell: 

```
touch  "$(echo -e ".abc\x8b\x8bThis is a bad filename")"
dmenu_extended_cache_build
```

**Comment by markjones112358** [comment]
Yuck! This has cropped up before when saving the cache, but I've never seen it happen in an `os.walk` call. This adds some weight to writing an implementation of the os.walk in python (or finding an alternative) as you mentioned in another issue.

Thanks for adding the steps to reproduce the error, that's handy.
I'll think on this during the week and hopefully get a chance to try next weekend.

**Comment by trqx** [comment]
Not an actual fix for dmenu-extended, but running `convmv -f windows-1252 -t utf8 -r ~ --notest` to convert filenames recursively to utf8 allowed me to run dmenu-extended without trouble.

**Comment by edi9999** [comment]
Thanks, that works well !

**Comment by MarkHedleyJones** [comment]
Closing as I believe this is no longer an issue under Python3. If there are any issues, please feel free to reopen.
