### ISSUE TITLE
Change Tab behaviour to jump to next hit instead of completion

### ISSUE THREAD

**Issue by GijsTimmers** [MarkHedleyJones/dmenu-extended#50]
Hi,

Currently, `dmenu_extended` applies the arrow keys to move to the next/previous completion after typing in part of the search term.

As a heavy vim user, this behaviour feels odd to me. My fingers are moved way too far from the middle keyboard row.

Is it possible to move to the next item with <kbd>Tab</kbd> instead of the arrow keys?

**Comment by markjones112358** [comment]
Hi.
Sorry but the menu navigation is handled by dmenu itself. Dmenu_extended only knows about the menu's inputs (things to display) and outputs (text back from the user).
To solve this issue you would need a patched version of dmenu (or maybe it's possible with rofi) that supports command mode / insert mode so you can use the letter keys for navigation.

I've got around this by having an ergodox keyboard where the arrow keys are on the home row when I use a layer modifier. I realise this probably doesn't help much, but there are alternative ways to get more natural behaviour.

**Comment by MarkHedleyJones** [comment]
Closing as the requested feature needs to be implemented in dmenu itself, not dmenu-extended.
