### ISSUE TITLE
Can't access folders/files with characters like "ç, ã, é"

### ISSUE THREAD

**Issue by vinieich** [MarkHedleyJones/dmenu-extended#51]
If I create a folder like "test" and add a file "test.pdf", the file is indexed and that's the normal behavior.
But if I create "test/testç.pdf", the file isn't indexed nor it appear on any cache file at .config/dmenu-extended/cache.
Also if I create "testç" and put the files "test.pdf" and "exampleç.pdf", even if the folder is recorded at dmenuExtended_folders.txt, the files are not.
Anyway I hope I'm being clear because english is not my mother language.
Thanks in advance!
PS: I use utf-8 scheme.

**Comment by markjones112358** [comment]
Hi there,
I think I understand what you're saying, I am also using UTF8.
I've had struggles in the past with non-english characters, debugging these problems gets hard because I don't really know how to handle them correctly.
I'm finding that if I launch `dmenu_extended_run` from a keybind (i3 exec statement) then opening the files and folders you've given fail.
However, If I run `dmenu_extended_run` from within a terminal everything works as expected.
Maybe it is something to do with environment variables not being loaded?

Are you able to try launching `dmenu_extended_run` from a terminal, rebuilding your cache from that terminal launched menu, then relaunching `dmenu_extended_run` from the terminal and opening those files for me and let me know if that also works for you?

**Comment by vinieich** [comment]
Hey Mark,
I tried running from terminal the `dmenu_extended_run` and updating the cache from the menu and also tried `dmenu_extended_cache_build` but the problem continued.
I'm no programmer, but I tinkered a little today and set the debug flag on the `dmenu_extended.py` and this is what I got:
PS: the stdout was just the names of the files and folders.

vinieich@archeve> dmenu_extended_cache_build > /dev/null                                                                     ~/descomplica
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dmenu_extended.py", line 666, in cache_save
    f.write(item+"\n")
  File "/usr/lib/python3.6/codecs.py", line 718, in write
    return self.writer.write(data)
  File "/usr/lib/python3.6/codecs.py", line 376, in write
    data, consumed = self.encode(object, self.errors)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce3' in position 88: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dmenu_extended_cache_build", line 6, in <module>
    dmenu_extended.dmenu().cache_build()
  File "/usr/lib/python3.6/site-packages/dmenu_extended.py", line 1076, in cache_build
    self.cache_save(filenames, file_cache_files)
  File "/usr/lib/python3.6/site-packages/dmenu_extended.py", line 683, in cache_save
    print('Culprit: ' + item)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udce3' in position 97: surrogates not allowed

Then searching about this error got me to this page:
[https://stackoverflow.com/questions/27366479/python-3-os-walk-file-paths-unicodeencodeerror-utf-8-codec-cant-encode-s](url)

I made sure that my files and folders already has the filename as UTF-8.
Like I said, I don't know python programming (or any other by the way) but that link may help.

Thanks for trying to solve this. I tried but luck can only get me to a certain point lol

**Comment by markjones112358** [comment]
Thanks for your response.
Have you tried the suggestion of trqx on this page: https://github.com/markjones112358/dmenu-extended/issues/38
That might help, it has for others.

**Comment by vinieich** [comment]
Sorry, I thought that I'd mentioned that.
Yes, that's why I was certain that I already has UTF-8 filename encoding.
I'll paste the output here:

convmv -f windows-1252 -t utf8 -r testcaseçç                                                                     ~/Documents
Starting a dry run without changes...
Skipping, already UTF-8: testcaseçç/thesecóndtestcase
Skipping, already UTF-8: ./testcaseçç
No changes to your files done. Would have converted 0 files in 0 seconds.
Use --notest to finally rename the files.

And this was the same for the production folders.
That link that I posted didn't give any light into it?
I ask because it was almost like alien language to me, but I'll try to understand that when I have some time.

Thanks in advance.

**Comment by vinieich** [comment]
Ok, found the problem.
There was a file that wasn't encoded on utf-8 hidden in my folders.

The problem is, when `dmenu-extended` find such files, it automagically delete all other files from cache that contain foreign character even if it is already in UTF-8.
You can reproduce this just by converting any UTF-8 folder to windows-1252.
After that, all files/folders with foreign characters (á, ç, õ") will vanish from cache
At least for me this is how it is happening.

**Comment by vinieich** [comment]
I'm closing this issue as the workaround works.
But probably the automagically delete thing still happens.
