### ISSUE TITLE
Feature Request: Open specific file extension with a specific program

### ISSUE THREAD

**Issue by hillz2** [MarkHedleyJones/dmenu-extended#57]
Hi

Your program has helped me a lot and I use it every day. I'm really thankful for that. I use ncmpcpp as the music player and vlc as the video player on my PC. Right now if I search for a song it will be played with vlc (I set **"fileopener": "vlc"**) It would be great if we could open specific file extensions with specific programs. Perhaps you could add an option to do that in the config file ?

**Comment by MarkHedleyJones** [comment]
Hi there,
Sorry it has taken so long to get back to you, and thanks for using dmenu-extended.
Setting `"fileopener": "vlc"` would very much limit your ability to open files with specific programs. The idea is that the default fileopener 'xdg-open` would choose the correct program based on what default program you have configured for xdg-open (I'm not actually sure how to set defaults for xdg-open, but a google will help there). Alternatively, `gnome-open` will choose the default application that a file would open with in gnome (you may or may not have gnome installed so this may be missing depending on your system configuration, but you could just try it) and that's much easier to set default applications (Right click file, properties, open with, choose appropriate program, click set as default).
What I'm trying to say is: you should configure your system file handlers to open files with the programs you want, and let those system file handlers (xdg-open, or gnome-open etc.) handle your file opening requests from dmenu-extended.

Does that make sense?

Thanks again,

Mark

**Comment by hillz2** [comment]
Thanks, using xdg-open solved the problem `"fileopener": "xdg-open"`
