### ISSUE TITLE
Background transparency 

### ISSUE THREAD

**Issue by kartongsaft** [MarkHedleyJones/dmenu-extended#59]
Hi!

Is it possible to use background transparency? If not, could this be implemented? Thanks in advance!

**Comment by MarkHedleyJones** [comment]
Hi there,
It doesn't support transparency out-of-the-box. The window drawing is handled by dmenu and isn't something that dmenu-extended has access to.
One route to making a transparent menu would be to patch your version of dmenu and use something like Compton to render the menu with opacity. Info on achieving this is available here: https://github.com/chjj/compton/issues/257
A second route would be to use a recent version of rofi as the menu and customise the colours with transparency. Rofi is supported by dmenu-extended so you can keep the same functionality. Some info on that is available here: https://github.com/DaveDavenport/rofi/issues/338

Hopefully that helps.

**Comment by kartongsaft** [comment]
Ah, I see! Well in that case, maybe I should try to contact the developer and see if that can be arranged in upcoming versions. I tried Rofi for a while, but later on realized that it wasn't my kind of coffee, even though it does the job. Thanks for your time!
