### ISSUE TITLE
Extra '/' required?

### ISSUE THREAD

**Issue by zidongtuili** [MarkHedleyJones/dmenu-extended#62]
https://github.com/MarkHedleyJones/dmenu-extended/blob/71701971051c3a874380ca2659d3e6020917a6b0/dmenu_extended.py#L1044

Maybe we should add +'/' like 1056 here?

**Comment by MarkHedleyJones** [comment]
Hi Zidongtuili,
Good point, that isn't going to match against ignore_folders entries with trailing slashes.
I think a better solution would be to strip the trailing slash from each entry in the ignore_folders list for the comparison. That would then cause a positive match for either case (with or without a trailing slash).
Is this something you would like to do and I pull and merge or shall I do?

**Comment by zidongtuili** [comment]
Hi MarkHedleyJones,
I'd love to do this. I had some changes, and I'm not sure how to do this that I can have 2 braches, one for the general fix and one for my personal taste?

**Comment by MarkHedleyJones** [comment]
I  just had a look at your fork and it seems you've made a few non-relevant changes in the same commit (such as editing the default preferences).
If I were you I'd fork my repository again, make only the changes that resolve the issue you're trying to fix, and then issue a merge request to me with that commit.

A tip with the configuration file... You don't need to edit the one in dmenu-extended.py as it gets overwritten by your local version at ~/.config/dmenu-extended/config/dmenuExtended_preferences.txt.
That file can be accessed easily using the Settings menu: -> Settings, Edit menu preferences.

**Comment by zidongtuili** [comment]
I saw the txt file, and I though it was a cache (which loaded settings from .py). -> settings didn't work for me, so I never knew how it worked.
I'm using a machine with scientific linux, no root permission, so there are always issues (that's why I gave up about settings).

**Comment by MarkHedleyJones** [comment]
Have made the relevant change to remove different behaviour between ignore folders with or without a trailing slash.
