### ISSUE TITLE
rofi window support

### ISSUE THREAD

**Issue by marlonschroder** [MarkHedleyJones/dmenu-extended#67]
it would be great if you had the option to add the rofi window support!

**Comment by MarkHedleyJones** [comment]
Hi Marlonschroder,
See [Running Dmenu-extended with Rofi](https://github.com/MarkHedleyJones/dmenu-extended#running-dmenu-extended-with-rofi) in the Readme and let me know if that doesn't cater to what you're looking for.

Cheers
