### ISSUE TITLE
Store cache in XDG_CACHE_HOME

### ISSUE THREAD

**Issue by duckdalbe** [MarkHedleyJones/dmenu-extended#74]
I'd like to suggest to store cache data not in the configuration directory but in `$XDG_CACHE_HOME`. Many people (like me) versionize or synchronize their configuration files — but not cached data (because it's not essential, blows up repositories, changes constantly). Keeping the types of data in different directories helps a lot.

The [freedesktop basedir specifications](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) also suggest this:

> $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used. 

Thank you for maintaining this useful software!

**Comment by MarkHedleyJones** [comment]
Thank's for pointing this out. It sounds logical and I totally agree.

**Comment by MarkHedleyJones** [comment]
@duckdalbe, latest update from @mg979 should address this.
See [5ed6a4c9ae6bc6282f6fd38ea2e69f6c732437e2](https://github.com/MarkHedleyJones/dmenu-extended/pull/75/commits/5ed6a4c9ae6bc6282f6fd38ea2e69f6c732437e2)

**Comment by MarkHedleyJones** [comment]
Closing as previously addressed
