### ISSUE TITLE
systemd service for dmenu_extended_cache_build does not run

### ISSUE THREAD

**Issue by ardunn** [MarkHedleyJones/dmenu-extended#84]
I seem to have successful installation except for the fact that the dmenu_extended_cache_build .service does not run (after running systemd-install.sh script). The cache is never updated and new files do not seem to be tracked?

This might be linked to #53 

Edit: I should mention I am running Mint 19.1 with XFCE4.

**Comment by MarkHedleyJones** [comment]
Hi,
Do you have a system-wide installation or a local user installation?
Also, if you run `systemctl`, can you see *update-dmenu-extended-db* in the list of services anywhere?

**Comment by ardunn** [comment]
Global install. 
No, it does not seem to be in systemctl. So maybe the systemd-install.sh script did not work?

**Comment by TsukiZombina** [comment]
I have a similar problem, it doesn't update the nor read the cache files if I modify them manually, also when execute the cache script it seems to have a memory leak, after I run it, the memory in my computer starts being consumed until it runs out.

**Comment by MarkHedleyJones** [comment]
Issues with `dmenu_extended_cache_build` should be resolved as of #135.
Closing this issue.
If you have any more issues please feel free to re-open this issue or create a new one.
