### ISSUE TITLE
How do I uninstall this? 

### ISSUE THREAD

**Issue by ghost** [MarkHedleyJones/dmenu-extended#85]
I'm sorry. I am new to this and I don't know how.

**Comment by MarkHedleyJones** [comment]
Hi @emesario,
Sorry, it has taken so long to respond to you!
Currently there isn't a one-command uninstall option.
But you can completely remove dmenu-extended by:
1. move into the cloned dmenu-extended folder (e.g. `cd ~/repos/dmenu-extended`)
2. re-run the setup and record the file locations `sudo python setup.py install --record files.txt`
3. remove each of the entries in files.txt (e.g. `sudo rm $(cat files.txt)`

I hope to make this process easier in future by adding the package to pip and allowing pip to handle installation and removal.

**Comment by MarkHedleyJones** [comment]
Closing as this information is now out-of-date.
